config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'videos#index'

  get 'videos/show'
  get "/signup",    to: 'users#new'
  get "/signup",    to: 'users#create'
  get '/choose',    to: 'sessions#choose'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  require 'Consumer'

  # Render /session/new.html.erb view for login and stores request source page
  #
  # @return [nil]
  def new
    session[:return_to] ||= request.referer
  end

  # Search for an already created user, if not, creates new user in DB and if
  # user credentials are valid it concedes permission to see the selected video
  #
  # @return [nil]
  def create
    if !logged_in?
      user = ApplicationRecord::User.find_by(email: params[:session][:email].downcase)
      if user
        if Consumer.get_token_status(user.access_token)
          log_in user
          redirect_to videos_show_url(id: session.delete(:video_id))
        else
          destroy
          if update_user_at_refresh_token(user.refresh_token, email)
            log_in user
            redirect_to videos_show_url(id: session(:video_id))
          else
            redirect_to root_url
          end
        end
      else
        response = Consumer.auth_consumer(params[:session][:email], params[:session][:password])
        if response.success?
          user = User.create(access_token: response.parsed_response["access_token"],
                              expires_in: response.parsed_response["expires_in"],
                              refresh_token: response.parsed_response["refresh_token"],
                              scope: response.parsed_response["scope"],
                              created_at: response.parsed_response["created_at"],
                              token_type: response.parsed_response["token_type"],
                              email: params[:session][:email]
                            )
          if user.save
            log_in user
          else
            render 'new'
          end
        else
          flash[:error] = 'Invalid email/password combination'
          render action: 'new'
        end
      end
    else
      redirect_to videos_show_url(id: session.delete(:video_id))
    end
  end

  def choose
    render 'choose'
  end

  # Destroy the current session (Logout) and returns to root url
  #
  # @return [nil]
  def destroy
    log_out
    redirect_to root_url
  end

  # Aux method that updates user info when token is refreshed in zype's api
  #
  # @param [string] refresh_token string stored when user log in
  # @param [email] email user email
  # @return [boolean] returns true if user is updated and false if not
  def update_user_at_refresh_token(refresh_token, email)
    response = Consumer.refresh_token(user.refresh_token)
    if response.success?
      db_user = ApplicationRecord::User.find_by_email(email)
      db_user.access_token = response["access_token"]
      db_user.expires_in = response["expires_in"]
      db_user.refresh_token = response["refresh_token"]
      db_user.created_at = response["created_at"]
      db_user.token_type = response["token_type"]
      if db_user.save?
        true
      else
        false
      end
    else
      false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Creates but not store the ActiveRecord::User and renders the user/new.html.erb
  #
  # @return [ActiveRecord::User]
  def new
    @user = User.new
  end

  # Creates a new ActiveRecord::User and store it in the database. If User is stored
  # without errors the user is logged in and flash welcome message. If user is not
  # stored without errors renders new view.
  #
  #
  # @return [ActiveRecord:User] 
  def create
    @user = User.new(params[:user])
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      #TODO: if save is successful redirect to video
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :passsword, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  require 'Video'

  # This method renders zype's video list on /video/index.html.erb
  #
  # @return [json] returns a video list in json format
  def index
    # video = Video.new()
    @video_list = Video.get_list()
  end

  # This method shows a selected video
  #
  # @return [nil]
  def show
    @video = Video.get_video(params[:id])
    @vid_id = params[:id]
    if !@video["suscription_required"]
      if logged_in?
        render 'show'
      else
        session[:video_id] = @vid_id
        redirect_to choose_url and return
        # TODO: render user_login screen
      end
    else
      render 'show'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Store in session variable the given user id
  #
  # @param [ActiveRecord::User] ActiveRecord::User - Model created in rails named User
  # @return [session] session variable
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the ActiveRecord::User retrieve with user_id
  #
  # @return [ActiveRecord::User] ActiveRecord::User
  def current_user
    @current ||= User.find_by(id: session[:user_id])
  end

  # Returns true if current user is not nil, returns false if its nil
  #
  # @return [boolean]
  def logged_in?
    !current_user.nil?
  end

  # Deletes user_id from the session variable and set @current_user to nil
  #
  # @return [nil]
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zype</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Suscribe') %>
<h1>Suscribe</h1>

<div class="container">
  <div class="row">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%# render 'shared/error_messages' %>
      <div class="row">
        <%= f.text_field :email, placeholder: "email" %>
      </div>
      <div class="row">
        <%= f.password_field :password, placeholder: "password" %>
      </div>
      <div class="row">
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
      </div>
      <div class="row">
        <%= f.submit "Send" %>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/_videodetail.html.erb
<% if !@video.nil? %>
  <div class="container video-info-container">
    <div class="row subc-row" id="video-container">
      <div id="zype_<%= @vid_id %>" class="zype-video-player">
      </div>
      <script src="https://player.zype.com/embed/<%= @vid_id %>.js?autoplay=true&app_key=<%= ENV["app_key"] %>" type="text/javascript">
      </script>
    </div>
    <div class="row subc-row">
      <h4 class="row-title">Title: </h4>
    </div>
    <div class="row subc-row">
      <%= @video["title"] %>
    </div>
    <div class="row subc-row">
      <h4 class="row-title">Description: </h4>
    </div>
    <div class="row subc-row">
      <%= @video["description"] %>
    </div>
  </div>
<% end %>

app/views/videos/_videowrapper.html.erb
<% if !@video_list.nil? %>
  <div class="row">
    <% @video_list.each do |video| %>
      <div class="video-wrapper col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <a href=<%= videos_show_path(id: video["_id"]) %> class="video-link">
          <div class="video-container">
            <img class="video-img" src="<%= video["thumbnails"][1]["url"]  %>" alt="">
            <div class="video-title">
              <%= video["title"] %>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/index.html.erb
<div class="container video-list-container">
  <%= render "videowrapper" %>
</div>

app/views/videos/show.html.erb
<% if !@video.nil? %>
  <% if @video["suscription_required"] %> <%# TODO: add ! to condition  %>
    <% if logged_in? %>
      <%= render "videodetail" %>
    <% end %>
  <% else %>
    <%= render "videodetail" %>
    <%# redirect_to login_url and return %>
  <% end %>
<% else %>

<% end %>